dataSet<-read.csv(file.choose(), header=TRUE, sep="\t")
##########################################################################################
# Variables
pts<-(dataSet$pts)
fgm<-(dataSet$fgm)
fga<-(dataSet$fga)
fg3<-(dataSet$fg3)
fg3a<-(dataSet$fg3a)
ftm<-(dataSet$ftm)
fta<-(dataSet$fta)
totrb<-(dataSet$totrb)
turnovr<-(dataSet$turnovr)
stl<-(dataSet$stl)
#############################################
# get stat means from non-vermont/umbc games
print(mean(pts))
print(mean(fgm))
print(mean(fga))
print(mean(fg3))
print(mean(fg3a))
print(mean(ftm))
print(mean(fta))
print(mean(totrb))
print(mean(turnovr))
print(mean(stl))
##########################################################################################
# Graphics #
##########################################################################################

# Format visual output screen
par(mfrow=c(3,2))

############################################
# effective field goal pecentage
efg = 100 * (fgm + 1.5*fg3 + .5*ftm) / (fga + fg3a + fta)
#print(efg)
#plot(efg,winLoss,xlab="efg",ylab="winLoss")
plot(efg,pts,xlab="Effective Field Goal %",ylab="Points Scored")
fit<-lm(pts~efg)
abline(fit, col="blue")
print(fit)
print("variance efg:",quote=F)
print(var(efg))
print("covariance efg,points:",quote=F)
print(cov(efg,pts))
print("correlatioin efg,points:",quote=F)
print(cor(efg,pts))
############################################
# rebounds
#print(offrb)
#print(defrb)
#plot(totrb,winLoss,xlab="rebounds",ylab="wins and losses")
plot(totrb,pts,xlab="Total Rebounds",ylab="Points Scored")
fit4<-lm(pts~totrb)
abline(fit4)
print(fit4)
print("variance total rebounds:",quote=F)
print(var(totrb))
print("covariance total rebounds,points:",quote=F)
print(cov(totrb,pts))
print("correlation total rebounds, points:",quote=F)
print(cor(totrb,pts))
############################################
# turnovers
#print(turnovr)
#plot(turnovr,winLoss,xlab="turnovers",ylab="wins and losses")
plot(turnovr,pts,xlab="Turnovers",ylab="Points Scored")
fit2<-lm(pts~turnovr)
abline(fit2, col='red')
print(fit2)
print("variancnce turnovers:",quote=F)
print(var(turnovr))
print("covariance turnovers,points:",quote=F)
print(cov(turnovr,pts))
print("correlation turnovers,points:",quote=F)
print(cor(turnovr,pts))
###########################################
# steals
#print(stl)
#plot(stl,winLoss,xlab="steals",ylab="wins and losses")
plot(stl,pts,xlab="Steals",ylab="Points Scored")
fit3<-lm(pts~stl)
abline(fit3, col= "green")
print(fit3)
print("variance steals:",quote=F)
print(var(stl))
print("covariance steals,points:",quote=F)
print(cov(stl,pts))
print("correlation steals,points:",quote=F)
print(cor(stl,pts))
##############################################
# # turnover rate
# torate<-(turnovr/(fga+fta+fg3a))
# plot(torate,pts)
# fit9<-lm(pts~torate)
# abline(fit9, col='red')
# print(fit9)
# print("variance turnover rate:",quote=F)
# print(var(torate))
# print("covariance turnover rate,points:",quote=F)
# print(cov(torate,pts))
# print("correlation turnover rate,points:",quote=F)
# print(cor(torate,pts))
##############################################
# steal to turnover margin
tovr<-(stl-turnovr)
plot(tovr,pts,xlab="Steal to Turnover Margin",ylab="Points Scored")
fit10<-lm(pts~tovr)
abline(fit10, col="blue")
print(fit10)
print("variance steal to turnover margin:",quote=F)
print(var(tovr))
print("covariance steal to turnover margin,points:",quote=F)
print(cov(tovr,pts))
print("correlation steal to turnover margin,points:",quote=F)
print(cor(tovr,pts))
##############################################

print("",quote=F)
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$", quote=F)
print("Score Model:",quote=F)

#fit99<-lm(pts~efg+tovr+totrb)
fit99<-lm(pts~efg+totrb)
print(fit99)
print(summary(fit99))
#print(vcov(fit99))
plot(fit99$residuals)
print("mean efg:",quote=F)
print(mean(efg))
print("mean turnover margin:",quote=F)
print(mean(tovr))
print("mean total rebounds:",quote=F)
print(mean(totrb))
